### PR TITLE
Feature/settings

### PR DESCRIPTION
**Pull request by mahmoudyousef98**
***For All Submissions:***

*Proposed Changes:*

Implemented set and get settings. Also changed the GUI constructor to be more in line with settings data logic. Also corrected some of the test cases (typos on my end)

*Testing Instructions:*

* [X ] Does simply running `pytest` suffice?

**Finally**,
* [X ] Have you updated the version number, by running `git tag v0.x`?

------

**For new features:**
* [n/a ] If you have used new packages, have you remade `requirements.txt` (explained in README)?

**For new tests:**
* [ n/a] Have you made sure your tests are in the `tests/` dir?
* [ n/a] Have you made sure your tests are in a file that starts with '`test_`'?
* [ n/a] Have you made sure your test functions starts with '`test_`'?

### CODE REVIEW

**Comment by ralph122** [comment]
Also note that `test/sampleVideo/test.mp4` is changed in one of the commits. The file is currently being modified whenever the tests are run. If this is a stable version of the file then it might be good.

**Comment by mahmoudyousef98** [comment]
Sure, I'll make the changes that you suggested.

And as for `test/sampleVideo/test.mp4`, I'm only concerned as to whether the file exists or not for my test cases. I'm not doing anything to it.

**Comment by ralph122** [comment]
I'm wondering if we need to add a unit test for the new method. The implementation looks good to me.

**Comment by mahmoudyousef98** [comment]
I don't think so because this is intended to be a "private" method, so theoretically shouldn't be able to call it publically.

**Pull request merged**
